# -*- coding: utf-8 -*-
"""Class_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0XR6FJQ7EERb12TcjLA7RZXjbKWWVkr

**Concatenation**
"""

print('hello,'+'world')

"""**Indexing**"""

a = 'hello'
print(a[4])

"""**Slicing**
start
end
steps
"""

fruits = ['apple','banana','melons']
print(fruits[1:3])
print(fruits[:])
print(fruits[::-1])
print(fruits[1:3:2])

"""**len**"""

print(len('fruits'))

"""**methods**"""

print(dir(str))

[method for method in dir(str) if '__' not in method]

"""lower case
upper case
title
split
"""

a = "hello world"
print(a.upper())
print(a.lower())
print(a.title())
print(a.split())

"""split remove space and words"""

a = "hello world"

print(a.split())

""".join use for multiple string convert into one string"""

# join the words back into a single string
my_string: str = ', '
joined_string: str = my_string.join(['Pakistan', 'USA', 'Canada', 'France', 'Japan'])
print(joined_string)  # Pakistan, USA, Canada, France, Japan

""".replace replace the word"""

my_string: str = "Hello, World! Hello, Pakistan"
# replace a substring
my_string = my_string.replace('Hello', 'Salam Walikum')
print(my_string)  # prints 'Salam Walikum, World! Salam Walikum, Pakistan'

""".find find index"""

my_string: str = "Hello, World! Hello, Pakistan"
# find the index of a substring
starting_index = my_string.find('World') # Index value of the first occurance of the word 'Hello'
print("starting_index = ", starting_index)  # prints 0

# Now lets find the second occurance of the word 'Hello'
# index value start from zero

starting_index2: str = starting_index + len("Hello") #len=5

print(my_string[starting_index2:] ) # after slicing ", World! Hello, Pakistan
print(my_string[starting_index2:].find("Hello")) # Starting index 9, because of slicing ", World! Hello, Pakistan"

"""interned"""

import sys
a = sys.intern("hello world!")
b = sys.intern("hello world!")
print(a is b)  # True (manually interned)